name: 'financial_sentiment_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'financial_sentiment'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models with proper materialization
models:
  financial_sentiment_dbt:
    # Staging models - materialized as views for flexibility
    staging:
      +materialized: view
      +schema: staging
    # Intermediate models - materialized as tables for performance
    intermediate:
      +materialized: table
      +schema: intermediate
    # Marts - materialized as tables for final consumption
    marts:
      +materialized: table
      +schema: marts

# Configuring seeds
seeds:
  financial_sentiment_dbt:
    +schema: seeds
    stock_symbols:
      +column_types:
        symbol: varchar(10)
        company_name: varchar(100)
        sector: varchar(50)
    sentiment_keywords:
      +column_types:
        keyword: varchar(50)
        sentiment: varchar(20)
        weight: float

# Configuring tests
tests:
  financial_sentiment_dbt:
    +store_failures: true
    +warn_if: ">10"
    +error_if: ">100" 